server:
  port: 8081

spring:
  application:
    name: state-service
  profiles:
    active: default

cloud:
  config:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/